import type { Metadata } from "next";
import { Lora, Outfit } from "next/font/google";
import "./globals.css";
import PixelBackground from "./components/PixelBackground";

const outfit = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
});

const lora = Lora({
  variable: "--font-lora",
  subsets: ["latin"],
  style: ["normal", "italic"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${outfit.variable} ${lora.variable} antialiased`}>
        <div className="relative min-h-screen w-full overflow-hidden">
          <PixelBackground />
          <div className="relative z-20 min-h-screen">{children}</div>
        </div>
      </body>
    </html>
  );
}
